### ISSUE TITLE
エラー終了

### ISSUE THREAD

**Issue by deathmetalland** [deathmetalland/IkaLog#13]
```
[event] 17:46 on_game_finish  
trigger event
<ikalog.outputs.statink.StatInk object at 0x10b285080>: Gathered img_judge((720, 1280, 3))
[event] 17:58 on_result_judge  judge: win, knockout: False
<ikalog.scenes.result_detail.ResultDetail object at 0x10ba383c8>: switching to state _state_tracking
12 / 51  inliers/matched
<ikalog.scenes.result_detail.ResultDetail object at 0x10ba383c8>: auto_warp() function broke the image.
<ikalog.scenes.result_detail.ResultDetail object at 0x10ba383c8>: Falling back to auto_offset()
Traceback (most recent call last):
  File "IkaLog.py", line 41, in <module>
    engine.run()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 215, in run
    self.process_frame()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 181, in process_frame
    self.process_scene(scene)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 145, in process_scene
    r = scene.match(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/scenes/scene.py", line 91, in match
    self._matched = self.match_no_cache(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/scenes/stateful_scene.py", line 36, in match_no_cache
    return self._state(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/scenes/result_detail.py", line 612, in _state_tracking
    self.analyze(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/scenes/result_detail.py", line 474, in analyze
    img = self.auto_offset(context, img)
TypeError: auto_offset() takes 2 positional arguments but 3 were given
```

**Comment by deathmetalland** [comment]
https://github.com/hasegaw/IkaLog/commit/4d47cf7f2b9494d2d3763d20aeb1110ba7245203 で安定した
