### ISSUE TITLE
結果画面認識の数字がおかしい

### ISSUE THREAD

**Issue by deathmetalland** [deathmetalland/IkaLog#14]
https://stat.ink/u/deathmetalland/186041

下記の時点で誤認している

```
[event] 07:14 on_result_judge  judge: win, knockout: False
<ikalog.scenes.result_detail.ResultDetail object at 0x114aad2b0>: switching to state _state_tracking
86 / 153  inliers/matched
match2 0.049785 match 0.997399 > threshold 0.000000
ゲーム終了。 ステージ:タチウオパーキング ルール:ナワバリバトル 勝ち 69p 4K/8D 使用ブキ:もみじシューター チーム内順位: 3
スクリーンショット ./screenshots/ikabattle_20151225_222559.png を保存しました
```

https://stat.ink/u/deathmetalland/186070

結果画面認識でエラーが発生していた。

```
[event] 11:31 on_result_judge  judge: win, knockout: False
<ikalog.scenes.result_detail.ResultDetail object at 0x114aad2b0>: switching to state _state_tracking
77 / 135  inliers/matched
match2 0.051111 match 0.997383 > threshold 0.000000
Console.on_game_individual_result() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/console.py", line 96, in on_game_individual_result
    s = self.get_text_game_individual_result(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/console.py", line 77, in get_text_game_individual_result
    s = '%s %dK/%dD' % (s, me['kills'], me['deaths'])
TypeError: %d format: a number is required, not NoneType

<<<<<
スクリーンショット ./screenshots/ikabattle_20151225_223016.png を保存しました
```

**Comment by deathmetalland** [comment]
ナワバリに限らない
https://stat.ink/u/deathmetalland/186182

またnumpyのエラーが出てる

```
[event] 21:12 on_game_death_reason_identified  weapon = splatroller_collabo
<ikalog.scenes.game.dead.GameDead object at 0x114aa5c50>: switching to state _state_default
/usr/local/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/local/lib/python3.5/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
<ikalog.outputs.statink.StatInk object at 0x1142b4d30>: Discarded screenshots
[event] 21:17 on_game_finish  
trigger event
<ikalog.outputs.statink.StatInk object at 0x1142b4d30>: Gathered img_judge((720, 1280, 3))
[event] 21:24 on_result_judge  judge: lose, knockout: True
<ikalog.scenes.result_detail.ResultDetail object at 0x114aad2b0>: switching to state _state_tracking
75 / 129  inliers/matched
match2 0.038728 match 0.997598 > threshold 0.000000
ゲーム終了。 ステージ:デカライン高架下 ルール:ガチヤグラ 負け 1K/4D 使用ブキ:スプラチャージャー チーム内順位: 2 プレイ前ウデマエ A-
スクリーンショット ./screenshots/ikabattle_20151225_224009.png を保存しました
```

**Comment by deathmetalland** [comment]
うまくいったケースもある
https://stat.ink/u/deathmetalland/185874

**Comment by deathmetalland** [comment]
https://github.com/hasegaw/IkaLog/commit/9fac5247314a467b353868c2ffa22b2d4342cc0d この対応をマージすると発生する。

**Comment by deathmetalland** [comment]
https://github.com/hasegaw/IkaLog/commit/5b16f8a0cc108a62fd048c230423023dec01928f までは問題なし

**Comment by deathmetalland** [comment]
https://github.com/hasegaw/IkaLog/commit/4d47cf7f2b9494d2d3763d20aeb1110ba7245203 で安定した
