### ISSUE TITLE
死因の認識に失敗してる

### ISSUE THREAD

**Issue by deathmetalland** [deathmetalland/IkaLog#19]
https://stat.ink/u/deathmetalland/257618

```
Game Start. Stage: ハコフグ倉庫, Mode: ナワバリバトル
[event] 10:32 on_game_start  
<ikalog.scenes.game.start.GameStart object at 0x10e924860>: switching to state _state_default
Go!
[event] 10:39 on_game_go_sign  
You were splatted!
[event] 11:15 on_game_dead  
<ikalog.scenes.game.dead.GameDead object at 0x10e92f710>: switching to state _state_tracking
last_death_reason {}
Console.on_game_death_reason_identified() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/console.py", line 52, in on_game_death_reason_identified
    { 'cause_of_death': context['game']['last_death_reason']}
KeyError: 'last_death_reason'

<<<<<
StatInk.on_game_death_reason_identified() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/statink.py", line 624, in on_game_death_reason_identified
    reason = context['game']['last_death_reason']
KeyError: 'last_death_reason'

<<<<<
DebugLog.on_game_death_reason_identified() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/debug.py", line 60, in on_game_death_reason_identified
    s = "weapon = %s" % (context['game']['last_death_reason'])
KeyError: 'last_death_reason'

<<<<<
<ikalog.scenes.game.dead.GameDead object at 0x10e92f710>: switching to state _state_default
You were splatted!
[event] 12:06 on_game_dead  
<ikalog.scenes.game.dead.GameDead object at 0x10e92f710>: switching to state _state_tracking
last_death_reason {}
Console.on_game_death_reason_identified() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/console.py", line 52, in on_game_death_reason_identified
    { 'cause_of_death': context['game']['last_death_reason']}
KeyError: 'last_death_reason'

<<<<<
StatInk.on_game_death_reason_identified() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/statink.py", line 624, in on_game_death_reason_identified
    reason = context['game']['last_death_reason']
KeyError: 'last_death_reason'

<<<<<
DebugLog.on_game_death_reason_identified() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/debug.py", line 60, in on_game_death_reason_identified
    s = "weapon = %s" % (context['game']['last_death_reason'])
KeyError: 'last_death_reason'

<<<<<
<ikalog.scenes.game.dead.GameDead object at 0x10e92f710>: switching to state _state_default
You were splatted!
[event] 13:10 on_game_dead  
<ikalog.scenes.game.dead.GameDead object at 0x10e92f710>: switching to state _state_tracking
last_death_reason {}
Console.on_game_death_reason_identified() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/console.py", line 52, in on_game_death_reason_identified
    { 'cause_of_death': context['game']['last_death_reason']}
KeyError: 'last_death_reason'

<<<<<
StatInk.on_game_death_reason_identified() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/statink.py", line 624, in on_game_death_reason_identified
    reason = context['game']['last_death_reason']
KeyError: 'last_death_reason'

<<<<<
DebugLog.on_game_death_reason_identified() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/debug.py", line 60, in on_game_death_reason_identified
    s = "weapon = %s" % (context['game']['last_death_reason'])
KeyError: 'last_death_reason'

<<<<<
<ikalog.scenes.game.dead.GameDead object at 0x10e92f710>: switching to state _state_default
Game End.
<ikalog.outputs.statink.StatInk object at 0x10e507710>: Discarded screenshots
[event] 13:40 on_game_finish  
trigger event
<ikalog.outputs.statink.StatInk object at 0x10e507710>: Gathered img_judge((720, 1280, 3))
[event] 13:47 on_result_judge  judge: lose, knockout: False
<ikalog.scenes.result_detail.ResultDetail object at 0x10e9347f0>: switching to state _state_tracking
<ikalog.scenes.result_detail.ResultDetail object at 0x10e9347f0>: weapons recoginition started.
<ikalog.scenes.result_detail.ResultDetail object at 0x10e9347f0>: weapons recoginition done.
Results. Stage: ハコフグ倉庫, Mode: ナワバリバトル, Result: lose 1033p 0K/3D Weapon: momiji Rank in the team: 1
[event] 13:55 on_game_individual_result  
スクリーンショット ./screenshots/ikabattle_20160109_143746.png を保存しました
<ikalog.outputs.statink.StatInk object at 0x10e507710>: Gathered img_result ((720, 1280, 3))
<ikalog.scenes.result_gears.ResultGears object at 0x10e934ba8>: switching to state _state_tracking
<ikalog.scenes.result_detail.ResultDetail object at 0x10e9347f0>: switching to state _state_default
[event] 14:08 on_result_gears  
<ikalog.scenes.result_gears.ResultGears object at 0x10e934ba8>: switching to state _state_default
Watchdog fired. Closing current session
Game Session end.
<ikalog.outputs.csv.CSV object at 0x10e5071d0> (enabled = True)
<ikalog.outputs.printjson.JSON object at 0x10e5076a0> (enabled = True)
<ikalog.outputs.statink.StatInk object at 0x10e507710> (enabled = True)
nawabari scores = None
<ikalog.outputs.statink.StatInk object at 0x10e507710>: Encoded screenshot (1280x720 1106152 bytes)
<ikalog.outputs.statink.StatInk object at 0x10e507710>: Encoded screenshot (1280x720 1391063 bytes)
{'agent': 'IkaLog',
 'agent_version': '4db2dcb',
 'cash_after': 304360,
 'death': 3,
 'end_at': 1452317851,
 'events': '(Events)',
 'gears': {'clothing': {'primary_ability': 'quick_respawn',
                        'secondary_abilities': ['quick_respawn',
                                                'ink_saver_sub',
                                                'quick_respawn']},
           'headgear': {'primary_ability': 'ink_recovery_up',
                        'secondary_abilities': ['special_duration_up',
                                                'swim_speed_up',
                                                'swim_speed_up']},
           'shoes': {'primary_ability': 'special_saver',
                     'secondary_abilities': ['swim_speed_up',
                                             'ink_saver_main',
                                             'swim_speed_up']}},
 'his_team_color': {'hue': 214, 'rgb': [21, 121, 253]},
 'image_judge': '(PNG Data)',
 'image_result': '(PNG Data)',
 'kill': 0,
 'level': 50,
 'lobby': 'standard',
 'map': 'hakofugu',
 'my_point': 1033,
 'my_team_color': {'hue': 18, 'rgb': [222, 64, 0]},
 'players': [{'death': 1,
              'is_me': 'no',
              'kill': 7,
              'level': 28,
              'point': 1211,
              'rank_in_team': 1,
              'team': 'his',
              'weapon': 'promodeler_rg'},
             {'death': 2,
              'is_me': 'no',
              'kill': 5,
              'level': 31,
              'point': 1061,
              'rank_in_team': 2,
              'team': 'his',
              'weapon': 'bucketslosher'},
             {'death': 1,
              'is_me': 'no',
              'kill': 1,
              'level': 17,
              'point': 774,
              'rank_in_team': 3,
              'team': 'his',
              'weapon': 'splatroller'},
             {'death': 3,
              'is_me': 'no',
              'kill': 2,
              'level': 18,
              'point': 653,
              'rank_in_team': 4,
              'team': 'his',
              'weapon': 'bucketslosher'},
             {'death': 3,
              'is_me': 'yes',
              'kill': 0,
              'level': 50,
              'point': 1033,
              'rank_in_team': 1,
              'team': 'my',
              'weapon': 'momiji'},
             {'death': 5,
              'is_me': 'no',
              'kill': 4,
              'level': 27,
              'point': 619,
              'rank_in_team': 2,
              'team': 'my',
              'weapon': 'splatroller_collabo'},
             {'death': 7,
              'is_me': 'no',
              'kill': 1,
              'level': 44,
              'point': 303,
              'rank_in_team': 3,
              'team': 'my',
              'weapon': 'pablo'},
             {'death': 0,
              'is_me': 'no',
              'kill': 2,
              'level': 11,
              'point': 0,
              'rank_in_team': 4,
              'team': 'my',
              'weapon': 'splatroller_collabo'}],
 'rank_in_team': 1,
 'result': 'lose',
 'rule': 'nawabari',
 'start_at': 1452317670,
 'weapon': 'momiji'}
[event] 14:09 on_game_session_end  death_reasons = {}
<ikalog.outputs.statink.StatInk object at 0x10e507710>: POST https://stat.ink/api/v1/battle
<ikalog.outputs.statink.StatInk object at 0x10e507710>: POST Done.
```

**Comment by deathmetalland** [comment]
https://github.com/hasegaw/IkaLog/commit/292d1fc766d83846d6460de4df8c083223813296 で解消された
