### ISSUE TITLE
死因の認識時にエラー終了する

### ISSUE THREAD

**Issue by deathmetalland** [deathmetalland/IkaLog#20]
```
<ikalog.scenes.game.start.GameStart object at 0x10b969a20>: switching to state _state_tracking
ゲーム開始。ステージ: キンメダイ美術館, ルール: ナワバリバトル
[event] 00:35 on_game_start  
<ikalog.scenes.game.start.GameStart object at 0x10b969a20>: switching to state _state_default
Go!
[event] 00:41 on_game_go_sign  
やられた！
[event] 02:12 on_game_dead  
<ikalog.scenes.game.dead.GameDead object at 0x10b9728d0>: switching to state _state_tracking
votes={'nzap89': 47}
Traceback (most recent call last):
  File "IkaLog.py", line 41, in <module>
    engine.run()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 222, in run
    self.process_frame()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 185, in process_frame
    self.process_scene(scene)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 148, in process_scene
    r = scene.match(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/scenes/scene.py", line 91, in match
    self._matched = self.match_no_cache(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/scenes/stateful_scene.py", line 36, in match_no_cache
    return self._state(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/scenes/game/dead.py", line 121, in _state_tracking
    self.count_death_reason_votes(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/scenes/game/dead.py", line 73, in count_death_reason_votes
    context['game']['cause_of_death'].get(most_possible_id, 0) + 1
KeyError: 'cause_of_death'
IkaLog$ 
```

**Comment by deathmetalland** [comment]
https://github.com/hasegaw/IkaLog/commit/292d1fc766d83846d6460de4df8c083223813296  で解消された
