### ISSUE TITLE
ValueError: 'friend' is not in list

### ISSUE THREAD

**Issue by deathmetalland** [deathmetalland/IkaLog#22]
```
StatInk.on_game_session_end() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 59, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/statink.py", line 618, in on_game_session_end
    payload = self.composite_payload(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/statink.py", line 411, in composite_payload
    index = fes_rank_titles.index(current_title)
ValueError: 'friend' is not in list

<<<<<
[event] 94:12 on_game_session_end  death_reasons = {'bold_neo': 2}
```

**Comment by deathmetalland** [comment]
今回のフェスでも発生した。
まことからスーパーにランクアップするタイミング

```
StatInk.on_game_session_end() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 224, in _main_loop
    self.process_frame()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 177, in process_frame
    frame, t = self.read_next_frame()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 87, in read_next_frame
    frame = self.capture.read_frame()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/inputs/input.py", line 188, in read_frame
    img = self._read_frame_func()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/inputs/opencv_file.py", line 87, in _read_frame_func
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 63, in call_plugins
    getattr(op, event_name)(self.context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/statink.py", line 652, in on_game_session_end
    payload = self.composite_payload(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/statink.py", line 438, in composite_payload
    index = fes_rank_titles.index(current_title)
ValueError: 'friend' is not in list

<<<<<
```

**Comment by deathmetalland** [comment]
https://github.com/deathmetalland/IkaLog/commit/9e4b3a2ecdf6cf90a6cd4b3c3b062d577f3f3ffa 解決した
