### ISSUE TITLE
'AVFoundationCapture' object has no attribute 'select_device'

### ISSUE THREAD

**Issue by deathmetalland** [deathmetalland/IkaLog#23]
```
<ikalog.inputs.osx.avfoundation_capture.AVFoundationCapture object at 0x107a17358>: initializing class
Traceback (most recent call last):
  File "IkaLog.py", line 37, in <module>
    capture, OutputPlugins = IkaConfig().config()
  File "/Users/deathmetalland/Workspace/IkaLog/IkaConfig.py", line 45, in config
    source.select_device(THE_DEVICE_ID)
AttributeError: 'AVFoundationCapture' object has no attribute 'select_device'
```

**Comment by deathmetalland** [comment]
select_device がないみたいなので、以前の start_camera に書き換えてみた

```
<ikalog.inputs.osx.avfoundation_capture.AVFoundationCapture object at 0x101acd2e8>: initializing class
<ikalog.inputs.osx.avfoundation_capture.AVFoundationCapture object at 0x101acd2e8>: start_camera() is deprcated. Use select_source().
   start_camera(index=1)
   start_camera(name="my capture device")
Traceback (most recent call last):
  File "IkaLog.py", line 37, in <module>
    capture, OutputPlugins = IkaConfig().config()
  File "/Users/deathmetalland/Workspace/IkaLog/IkaConfig.py", line 42, in config
    source.start_camera(0)    # デバイス名は環境による
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/inputs/input.py", line 278, in start_camera
    raise Exception()
Exception
```

**Comment by deathmetalland** [comment]
start_camera は非推奨で、 select_source を使うようにと

```
<ikalog.utils.icon_recoginizer.gearpower.GearPowerRecoginizer object at 0x10f24bd30>: KNN Trained (1010 samples)
Traceback (most recent call last):
  File "IkaLog.py", line 43, in <module>
    engine.run()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 221, in run
    self.process_frame()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 173, in process_frame
    frame, t = self.read_next_frame()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 83, in read_next_frame
    frame = self.capture.read_frame()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/inputs/input.py", line 180, in read_frame
    self._skip_frame_recorded()
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/inputs/input.py", line 155, in _skip_frame_recorded
    skip = video_msec < tick
UnboundLocalError: local variable 'tick' referenced before assignment
```

**Comment by deathmetalland** [comment]
サンプルのパターン6が有効のままでこれを無効にしたらエラー発生しなくなった。
