### ISSUE TITLE
start_video_file() is deprcated

### ISSUE THREAD

**Issue by deathmetalland** [deathmetalland/IkaLog#24]
```
<ikalog.inputs.opencv_file.CVFile object at 0x10ecef0b8>: start_video_file() is deprcated. Use select_source(name="filename.mp4")
```

**Comment by deathmetalland** [comment]
select_source を使うと下記エラーが発生する

```
Traceback (most recent call last):
  File "IkaLog.py", line 39, in <module>
    capture, OutputPlugins = IkaConfig().config()
  File "/Users/deathmetalland/Workspace/IkaLog/IkaConfig.py", line 53, in config
    source.select_source(sys.argv[2])
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/inputs/input.py", line 123, in select_source
    r = self._select_device_by_index_func(index)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/inputs/opencv_file.py", line 53, in _select_device_by_index_func
    '%s does not support selecting device by index.' % self)
Exception: <ikalog.inputs.opencv_file.CVFile object at 0x113305128> does not support selecting device by index.
```

**Comment by deathmetalland** [comment]
パラメータに name= で解決
