### ISSUE TITLE
最新だとエラー？

### ISSUE THREAD

**Issue by deathmetalland** [deathmetalland/IkaLog#36]
```
StatInk.on_game_session_end() raised a exception >>>>
Traceback (most recent call last):
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/engine.py", line 103, in call_plugin
    getattr(plugin, event_name)(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/statink.py", line 758, in on_game_session_end
    self._close_game_session(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/statink.py", line 750, in _close_game_session
    self.post_payload(context, payload)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/outputs/statink.py", line 666, in post_payload
    copied_context = IkaUtils.copy_context(context)
  File "/Users/deathmetalland/Workspace/IkaLog/ikalog/utils/ikautils.py", line 279, in copy_context
    return copy.deepcopy(context2)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 298, in _reconstruct
    state = deep copy(state, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 251, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 298, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 219, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 298, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copy.py", line 293, in _reconstruct
    y = callable(*args)
  File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/copyreg.py", line 88, in __newobj__
    return cls.__new__(cls, *args)
TypeError: object.__new__(_thread.lock) is not safe, use _thread.lock.__new__()

<<<<<
```

**Comment by deathmetalland** [comment]
安定してる
https://github.com/hasegaw/IkaLog/commit/5dc53a410529dc2c475e6e8e3f1a3679c26baeef
